/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author Halim Jayakusuma Wiradinata NIM A11.2022.14044
 */
public class FrameBaru extends javax.swing.JFrame {

    /**
     * Creates new form FrameBaru
     */
    public FrameBaru() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        angka1 = new javax.swing.JTextField();
        angka2 = new javax.swing.JTextField();
        tblKurang = new javax.swing.JButton();
        tblTambah = new javax.swing.JButton();
        tblKali = new javax.swing.JButton();
        tblBagi = new javax.swing.JButton();
        tblMod = new javax.swing.JButton();
        txtHasil = new javax.swing.JLabel();

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        angka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka1ActionPerformed(evt);
            }
        });

        tblKurang.setText("-");
        tblKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKurangActionPerformed(evt);
            }
        });

        tblTambah.setText("+");
        tblTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblTambahActionPerformed(evt);
            }
        });

        tblKali.setText("x");
        tblKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKaliActionPerformed(evt);
            }
        });

        tblBagi.setText("/");
        tblBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblBagiActionPerformed(evt);
            }
        });

        tblMod.setText("mod");
        tblMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tblTambah)
                        .addGap(18, 18, 18)
                        .addComponent(tblKurang)
                        .addGap(18, 18, 18)
                        .addComponent(tblKali)
                        .addGap(18, 18, 18)
                        .addComponent(tblBagi)
                        .addGap(18, 18, 18)
                        .addComponent(tblMod))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(angka1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(angka2)))
                .addGap(15, 15, 15)
                .addComponent(txtHasil, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtHasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(angka1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(angka2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tblKurang)
                            .addComponent(tblTambah)
                            .addComponent(tblKali)
                            .addComponent(tblBagi)
                            .addComponent(tblMod))))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKurangActionPerformed
        // TODO add your handling code here:
        // Jika angka tidak diisi
        if (angka1.getText().isEmpty() || angka2.getText().isEmpty()) {
            txtHasil.setText("Error: Both fields must be filled");
            return;
        }
        // Kalkulasi Kurang
        double hasil = Double.parseDouble(angka1.getText()) - Double.parseDouble(angka2.getText());
        txtHasil.setText(Double.toString(hasil));
    }//GEN-LAST:event_tblKurangActionPerformed

    private void tblTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblTambahActionPerformed
        // TODO add your handling code here:
        // Jika angka tidak diisi
        if (angka1.getText().isEmpty() || angka2.getText().isEmpty()) {
            txtHasil.setText("Error: Both fields must be filled");
            return;
        }
        // Kalkuasi tambah
        double hasil = Double.parseDouble(angka1.getText()) + Double.parseDouble(angka2.getText());
        txtHasil.setText(Double.toString(hasil));
    }//GEN-LAST:event_tblTambahActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKaliActionPerformed
        // TODO add your handling code here:
        // Jika angka tidak diisi
        if (angka1.getText().isEmpty() || angka2.getText().isEmpty()) {
            txtHasil.setText("Error: Both fields must be filled");
            return;
        }
        // Kalkulasi Kali
        double hasil = Double.parseDouble(angka1.getText()) * Double.parseDouble(angka2.getText());
        txtHasil.setText(Double.toString(hasil));
    }//GEN-LAST:event_tblKaliActionPerformed

    private void tblBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblBagiActionPerformed
        // TODO add your handling code here:
        // Jika angka tidak diisi
        if (angka1.getText().isEmpty() || angka2.getText().isEmpty()) {
            txtHasil.setText("Error: Both fields must be filled");
            return;
        }
        // Kalkulasi Bagi
        try {
            double num1 = Double.parseDouble(angka1.getText());
            double num2 = Double.parseDouble(angka2.getText());
            if (num2 == 0) {
                txtHasil.setText("Error: Division by zero");
            } else {
                double hasil = num1 / num2;
                txtHasil.setText(Double.toString(hasil));
            }
        } catch (NumberFormatException e) {
            txtHasil.setText("Error: Invalid input");
        } catch (Exception e) {
            txtHasil.setText("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_tblBagiActionPerformed

    private void tblModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblModActionPerformed
        // TODO add your handling code here:
        // Jika angka tidak diisi
        if (angka1.getText().isEmpty() || angka2.getText().isEmpty()) {
            txtHasil.setText("Error: Both fields must be filled");
            return;
        }
        // Kalkulasi Modulus
        double hasil = Double.parseDouble(angka1.getText()) % Double.parseDouble(angka2.getText());
        txtHasil.setText(Double.toString(hasil));
    }//GEN-LAST:event_tblModActionPerformed

    private void angka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angka1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameBaru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angka1;
    private javax.swing.JTextField angka2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton tblBagi;
    private javax.swing.JButton tblKali;
    private javax.swing.JButton tblKurang;
    private javax.swing.JButton tblMod;
    private javax.swing.JButton tblTambah;
    private javax.swing.JLabel txtHasil;
    // End of variables declaration//GEN-END:variables
}
